---
env_name: "production"
nginx_listen_port: 8082
app_run_port: 5002
app_dir_path: "/var/www/production_app"
app_debug_mode: "False"
db_connection_url: "sqlite:////var/www/production_app/production_db.sqlite"
db_port: 5433
